// Generated by CoffeeScript 2.3.1
(function() {
  var Jaguar, fatalError, fs, helpers, jakefileDirectory, missingTask, oparse, options, optparse, path, printTasks, switches, tasks;

  fs = require('fs');

  path = require('path');

  helpers = require('./helpers');

  optparse = require('./optparse');

  Jaguar = require('./');

  Jaguar.register();

  tasks = {};

  options = {};

  switches = {};

  oparse = null;

  helpers.extend(global, {
    task: function(name, description, action) {
      if (!action) {
        [action, description] = [description, action];
      }
      return tasks[name] = {name, description, action};
    },
    option: function(letter, flag, description) {
      return switches.push([letter, flag, description]);
    },
    invoke: function(name) {
      if (!tasks[name]) {
        missingTask(name);
      }
      return tasks[name].action(options);
    }
  });

  exports.run = function() {
    var arg, args, e, i, len, ref, results;
    global.__originalDirname = fs.realpathSync('.');
    process.chdir(jakefileDirectory(__originalDirname));
    args = process.argv.slice(2);
    Jaguar.run(fs.readFileSync('Jakefile').toString(), {
      filename: 'Jakefile'
    });
    oparse = new optparse.OptionParser(switches);
    if (!args.length) {
      return printTasks();
    }
    try {
      options = oparse.parse(args);
    } catch (error) {
      e = error;
      return fatalError(`${e}`);
    }
    ref = options.arguments;
    results = [];
    for (i = 0, len = ref.length; i < len; i++) {
      arg = ref[i];
      results.push(invoke(arg));
    }
    return results;
  };

  printTasks = function() {
    var desc, jakefilePath, name, relative, spaces, task;
    relative = path.relative || path.resolve;
    jakefilePath = path.join(relative(__originalDirname, process.cwd()), 'Jakefile');
    console.log(`${jakefilePath} defines the following tasks:\n`);
    for (name in tasks) {
      task = tasks[name];
      spaces = 20 - name.length;
      spaces = spaces > 0 ? Array(spaces + 1).join(' ') : '';
      desc = task.description ? `# ${task.description}` : '';
      console.log(`jake ${name}${spaces} ${desc}`);
    }
    if (switches.length) {
      return console.log(oparse.help());
    }
  };

  fatalError = function(message) {
    console.error(message + '\n');
    console.log('To see a list of all tasks/options, run "jake"');
    return process.exit(1);
  };

  missingTask = function(task) {
    return fatalError(`No such task: ${task}`);
  };

  jakefileDirectory = function(dir) {
    var parent;
    if (fs.existsSync(path.join(dir, 'Jakefile'))) {
      return dir;
    }
    parent = path.normalize(path.join(dir, '..'));
    if (parent !== dir) {
      return jakefileDirectory(parent);
    }
    throw new Error(`Jakefile not found in ${process.cwd()}`);
  };

}).call(this);
